### ISSUE TITLE
license of project?

### ISSUE THREAD

**Issue by mewmew** [benit8/hexdump#1]
Hej @benit8,

Thanks for releasing a pure and straight forward implementation of `hexdump`. It is a very useful project, especially since it's API makes it easy to use within other projects.

I tried to find license information related to the project but could not find any.

May I ask, how is this project licensed?

You are of course free to use whatever license you desire. If I may put in a personal wish, it would be for the `hexdump` project to be permissively licensed, e.g. using [BSD/MIT license](https://github.com/llir/llvm/blob/master/LICENSE) or [public domain/creative commons zero/unlicensed](https://github.com/llir/llvm/blob/master/UNLICENSE).

Wish you all the best and a happy start of the new year!

Cheers,
Robin

**Comment by benit8** [comment]
Hello Mewmew,

Thank you very much for your kind words.

I don't think I will license this project since it is so simple. I never even got to use it myself, but thought it wouldn't hurt to share it.

Feel free to use it as you wish, even make it better. You don't have to credit it in any way, though it would still be greatly appreciated :)

Best of wishes for 2022,
Benoît

**Comment by mewmew** [comment]
Thanks Benoît, that's lovely! <3

Best wishes!
Robin
